package ncl.pm.model.bc.vo;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;

import ncl.pm.model.bc.view.xxpmJC.ModelActions;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 11 14:11:10 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmWarpViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        WarpId {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getWarpId();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setWarpId((DBSequence)value);
            }
        }
        ,
        ImId {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getImId();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setImId((Number)value);
            }
        }
        ,
        Segment2 {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getSegment2();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setSegment2((String)value);
            }
        }
        ,
        BaseImId {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getBaseImId();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setBaseImId((Number)value);
            }
        }
        ,
        ImIdYB {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getImIdYB();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setImIdYB((Number)value);
            }
        }
        ,
        Description {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getDescription();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        MeasuringSystem {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getMeasuringSystem();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setMeasuringSystem((String)value);
            }
        }
        ,
        YarnCount {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getYarnCount();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setYarnCount((Number)value);
            }
        }
        ,
        YarnPlies {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getYarnPlies();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setYarnPlies((String)value);
            }
        }
        ,
        YarnType {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getYarnType();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setYarnType((String)value);
            }
        }
        ,
        YBResultant {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getYBResultant();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setYBResultant((String)value);
            }
        }
        ,
        YTResultant {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getYTResultant();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setYTResultant((String)value);
            }
        }
        ,
        ImIdYT {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getImIdYT();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setImIdYT((Number)value);
            }
        }
        ,
        CottonRatio {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getCottonRatio();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setCottonRatio((Number)value);
            }
        }
        ,
        FiberRatio {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getFiberRatio();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setFiberRatio((Number)value);
            }
        }
        ,
        WarpResultant {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getWarpResultant();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setWarpResultant((String)value);
            }
        }
        ,
        Denier1 {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getDenier1();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setDenier1((Number)value);
            }
        }
        ,
        Denier1Ratio {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getDenier1Ratio();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setDenier1Ratio((Number)value);
            }
        }
        ,
        Denier2 {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getDenier2();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setDenier2((Number)value);
            }
        }
        ,
        Denier2Ratio {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getDenier2Ratio();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setDenier2Ratio((Number)value);
            }
        }
        ,
        Draft1 {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getDraft1();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setDraft1((Number)value);
            }
        }
        ,
        Draft2 {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getDraft2();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setDraft2((Number)value);
            }
        }
        ,
        SlubCode {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getSlubCode();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setSlubCode((String)value);
            }
        }
        ,
        FancyYarnType {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getFancyYarnType();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setFancyYarnType((String)value);
            }
        }
        ,
        TotDenierRatio {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getTotDenierRatio();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setTotDenierRatio((Number)value);
            }
        }
        ,
        WarpGSM {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getWarpGSM();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setWarpGSM((Double)value);
            }
        }
        ,
        ConvertedYarnCount {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getConvertedYarnCount();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setConvertedYarnCount((Number)value);
            }
        }
        ,
        XxpmItemMasterWvView {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getXxpmItemMasterWvView();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SpinningItemDescLov {
            public Object get(XxpmWarpViewRowImpl obj) {
                return obj.getSpinningItemDescLov();
            }

            public void put(XxpmWarpViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxpmWarpViewRowImpl object);

        public abstract void put(XxpmWarpViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WARPID = AttributesEnum.WarpId.index();
    public static final int IMID = AttributesEnum.ImId.index();
    public static final int SEGMENT2 = AttributesEnum.Segment2.index();
    public static final int BASEIMID = AttributesEnum.BaseImId.index();
    public static final int IMIDYB = AttributesEnum.ImIdYB.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int MEASURINGSYSTEM = AttributesEnum.MeasuringSystem.index();
    public static final int YARNCOUNT = AttributesEnum.YarnCount.index();
    public static final int YARNPLIES = AttributesEnum.YarnPlies.index();
    public static final int YARNTYPE = AttributesEnum.YarnType.index();
    public static final int YBRESULTANT = AttributesEnum.YBResultant.index();
    public static final int YTRESULTANT = AttributesEnum.YTResultant.index();
    public static final int IMIDYT = AttributesEnum.ImIdYT.index();
    public static final int COTTONRATIO = AttributesEnum.CottonRatio.index();
    public static final int FIBERRATIO = AttributesEnum.FiberRatio.index();
    public static final int WARPRESULTANT = AttributesEnum.WarpResultant.index();
    public static final int DENIER1 = AttributesEnum.Denier1.index();
    public static final int DENIER1RATIO = AttributesEnum.Denier1Ratio.index();
    public static final int DENIER2 = AttributesEnum.Denier2.index();
    public static final int DENIER2RATIO = AttributesEnum.Denier2Ratio.index();
    public static final int DRAFT1 = AttributesEnum.Draft1.index();
    public static final int DRAFT2 = AttributesEnum.Draft2.index();
    public static final int SLUBCODE = AttributesEnum.SlubCode.index();
    public static final int FANCYYARNTYPE = AttributesEnum.FancyYarnType.index();
    public static final int TOTDENIERRATIO = AttributesEnum.TotDenierRatio.index();
    public static final int WARPGSM = AttributesEnum.WarpGSM.index();
    public static final int CONVERTEDYARNCOUNT = AttributesEnum.ConvertedYarnCount.index();
    public static final int XXPMITEMMASTERWVVIEW = AttributesEnum.XxpmItemMasterWvView.index();
    public static final int SPINNINGITEMDESCLOV = AttributesEnum.SpinningItemDescLov.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxpmWarpViewRowImpl() {
    }

    /**
     * Gets XxpmWarp entity object.
     * @return the XxpmWarp
     */
    public EntityImpl getXxpmWarp() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets XxpmYarnBlendRsltV entity object.
     * @return the XxpmYarnBlendRsltV
     */
    public EntityImpl getXxpmYarnBlendRsltV() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets XxpmYarnTypeRsltV entity object.
     * @return the XxpmYarnTypeRsltV
     */
    public EntityImpl getXxpmYarnTypeRsltV() {
        return (EntityImpl)getEntity(2);
    }

    /**
     * Gets the attribute value for WARP_ID using the alias name WarpId.
     * @return the WARP_ID
     */
    public DBSequence getWarpId() {
        return (DBSequence)getAttributeInternal(WARPID);
    }

    /**
     * Sets <code>value</code> as attribute value for WARP_ID using the alias name WarpId.
     * @param value value to set the WARP_ID
     */
    public void setWarpId(DBSequence value) {
        setAttributeInternal(WARPID, value);
    }

    /**
     * Gets the attribute value for IM_ID using the alias name ImId.
     * @return the IM_ID
     */
    public Number getImId() {
        return (Number)getAttributeInternal(IMID);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_ID using the alias name ImId.
     * @param value value to set the IM_ID
     */
    public void setImId(Number value) {
        setAttributeInternal(IMID, value);
    }

    /**
     * Gets the attribute value for SEGMENT2 using the alias name Segment2.
     * @return the SEGMENT2
     */
    public String getSegment2() {
        return (String)getAttributeInternal(SEGMENT2);
    }

    /**
     * Sets <code>value</code> as attribute value for SEGMENT2 using the alias name Segment2.
     * @param value value to set the SEGMENT2
     */
    public void setSegment2(String value) {
        setAttributeInternal(SEGMENT2, value);
    }

    /**
     * Gets the attribute value for BASE_IM_ID using the alias name BaseImId.
     * @return the BASE_IM_ID
     */
    public Number getBaseImId() {
        return (Number)getAttributeInternal(BASEIMID);
    }

    /**
     * Sets <code>value</code> as attribute value for BASE_IM_ID using the alias name BaseImId.
     * @param value value to set the BASE_IM_ID
     */
    public void setBaseImId(Number value) {
        setAttributeInternal(BASEIMID, value);
    }

    /**
     * Gets the attribute value for IM_ID using the alias name ImIdYB.
     * @return the IM_ID
     */
    public Number getImIdYB() {
        return (Number)getAttributeInternal(IMIDYB);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_ID using the alias name ImIdYB.
     * @param value value to set the IM_ID
     */
    public void setImIdYB(Number value) {
        setAttributeInternal(IMIDYB, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for MEASURING_SYSTEM using the alias name MeasuringSystem.
     * @return the MEASURING_SYSTEM
     */
    public String getMeasuringSystem() {
        return (String)getAttributeInternal(MEASURINGSYSTEM);
    }

    /**
     * Sets <code>value</code> as attribute value for MEASURING_SYSTEM using the alias name MeasuringSystem.
     * @param value value to set the MEASURING_SYSTEM
     */
    public void setMeasuringSystem(String value) {
        setAttributeInternal(MEASURINGSYSTEM, value);
    }

    /**
     * Gets the attribute value for YARN_COUNT using the alias name YarnCount.
     * @return the YARN_COUNT
     */
    public Number getYarnCount() {
        return (Number)getAttributeInternal(YARNCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for YARN_COUNT using the alias name YarnCount.
     * @param value value to set the YARN_COUNT
     */
    public void setYarnCount(Number value) {
        setAttributeInternal(YARNCOUNT, value);
    }

    /**
     * Gets the attribute value for YARN_PLIES using the alias name YarnPlies.
     * @return the YARN_PLIES
     */
    public String getYarnPlies() {
        return (String)getAttributeInternal(YARNPLIES);
    }

    /**
     * Sets <code>value</code> as attribute value for YARN_PLIES using the alias name YarnPlies.
     * @param value value to set the YARN_PLIES
     */
    public void setYarnPlies(String value) {
        setAttributeInternal(YARNPLIES, value);
    }

    /**
     * Gets the attribute value for YARN_TYPE using the alias name YarnType.
     * @return the YARN_TYPE
     */
    public String getYarnType() {
        return (String)getAttributeInternal(YARNTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for YARN_TYPE using the alias name YarnType.
     * @param value value to set the YARN_TYPE
     */
    public void setYarnType(String value) {
        setAttributeInternal(YARNTYPE, value);
    }

    /**
     * Gets the attribute value for RESULTANT using the alias name YBResultant.
     * @return the RESULTANT
     */
    public String getYBResultant() {
        return (String)getAttributeInternal(YBRESULTANT);
    }

    /**
     * Sets <code>value</code> as attribute value for RESULTANT using the alias name YBResultant.
     * @param value value to set the RESULTANT
     */
    public void setYBResultant(String value) {
        setAttributeInternal(YBRESULTANT, value);
    }

    /**
     * Gets the attribute value for RESULTANT using the alias name YTResultant.
     * @return the RESULTANT
     */
    public String getYTResultant() {
        return (String)getAttributeInternal(YTRESULTANT);
    }

    /**
     * Sets <code>value</code> as attribute value for RESULTANT using the alias name YTResultant.
     * @param value value to set the RESULTANT
     */
    public void setYTResultant(String value) {
        setAttributeInternal(YTRESULTANT, value);
    }

    /**
     * Gets the attribute value for IM_ID using the alias name ImIdYT.
     * @return the IM_ID
     */
    public Number getImIdYT() {
        return (Number)getAttributeInternal(IMIDYT);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_ID using the alias name ImIdYT.
     * @param value value to set the IM_ID
     */
    public void setImIdYT(Number value) {
        setAttributeInternal(IMIDYT, value);
    }

    /**
     * Gets the attribute value for COTTON_RATIO using the alias name CottonRatio.
     * @return the COTTON_RATIO
     */
    public Number getCottonRatio() {
        return (Number)getAttributeInternal(COTTONRATIO);
    }

    /**
     * Sets <code>value</code> as attribute value for COTTON_RATIO using the alias name CottonRatio.
     * @param value value to set the COTTON_RATIO
     */
    public void setCottonRatio(Number value) {
        setAttributeInternal(COTTONRATIO, value);
    }

    /**
     * Gets the attribute value for FIBER_RATIO using the alias name FiberRatio.
     * @return the FIBER_RATIO
     */
    public Number getFiberRatio() {
        return (Number)getAttributeInternal(FIBERRATIO);
    }

    /**
     * Sets <code>value</code> as attribute value for FIBER_RATIO using the alias name FiberRatio.
     * @param value value to set the FIBER_RATIO
     */
    public void setFiberRatio(Number value) {
        setAttributeInternal(FIBERRATIO, value);
    }


    /**
     * Gets the attribute value for the calculated attribute WarpResultant.
     * @return the WarpResultant
     */
    public String getWarpResultant() {
        //return (String) getAttributeInternal(WARPRESULTANT);
        String result = "";
        if (ma.totViewRows(this.getApplicationModule().findViewObject("XxpmWarpViewChild")) >
            1) {
            result =
                    (getYarnCount() != null ? getYarnCount() : "") + (getYarnCount() !=
                                                                      null &&
                                                                      getYarnPlies() !=
                                                                      null ?
                                                                      "/" :
                                                                      "") +
                    (getYarnPlies() != null ? getYarnPlies() : "");
            result = result.replaceAll("\\s+", " ").trim();
        } else {
            result =
                    (getYarnCount() != null ? getYarnCount() : "") + (getYarnCount() !=
                                                                      null &&
                                                                      getYarnPlies() !=
                                                                      null ?
                                                                      "/" :
                                                                      "") +
                    (getYarnPlies() != null ? getYarnPlies() : "") +
                    (getMeasuringSystem() != null ?
                     " " + getMeasuringSystem() : "") +
                    (getYarnType() != null ? " " + getYarnType() : "") +
                    (getYBResultant() != null ? " " + getYBResultant() : "") +
                    (getYTResultant() != null ? " " + getYTResultant() : "");
            result = result.replaceAll("\\s+", " ").trim();
        }
        return result;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WarpResultant.
     * @param value value to set the  WarpResultant
     */
    public void setWarpResultant(String value) {
        setAttributeInternal(WARPRESULTANT, value);
    }

    /**
     * Gets the attribute value for DENIER1 using the alias name Denier1.
     * @return the DENIER1
     */
    public Number getDenier1() {
        return (Number)getAttributeInternal(DENIER1);
    }

    /**
     * Sets <code>value</code> as attribute value for DENIER1 using the alias name Denier1.
     * @param value value to set the DENIER1
     */
    public void setDenier1(Number value) {
        setAttributeInternal(DENIER1, value);
    }

    /**
     * Gets the attribute value for DENIER1_RATIO using the alias name Denier1Ratio.
     * @return the DENIER1_RATIO
     */
    public Number getDenier1Ratio() {
        return (Number)getAttributeInternal(DENIER1RATIO);
    }

    /**
     * Sets <code>value</code> as attribute value for DENIER1_RATIO using the alias name Denier1Ratio.
     * @param value value to set the DENIER1_RATIO
     */
    public void setDenier1Ratio(Number value) {
        setAttributeInternal(DENIER1RATIO, value);
    }

    /**
     * Gets the attribute value for DENIER2 using the alias name Denier2.
     * @return the DENIER2
     */
    public Number getDenier2() {
        return (Number)getAttributeInternal(DENIER2);
    }

    /**
     * Sets <code>value</code> as attribute value for DENIER2 using the alias name Denier2.
     * @param value value to set the DENIER2
     */
    public void setDenier2(Number value) {
        setAttributeInternal(DENIER2, value);
    }

    /**
     * Gets the attribute value for DENIER2_RATIO using the alias name Denier2Ratio.
     * @return the DENIER2_RATIO
     */
    public Number getDenier2Ratio() {
        return (Number)getAttributeInternal(DENIER2RATIO);
    }

    /**
     * Sets <code>value</code> as attribute value for DENIER2_RATIO using the alias name Denier2Ratio.
     * @param value value to set the DENIER2_RATIO
     */
    public void setDenier2Ratio(Number value) {
        setAttributeInternal(DENIER2RATIO, value);
    }

    /**
     * Gets the attribute value for DRAFT1 using the alias name Draft1.
     * @return the DRAFT1
     */
    public Number getDraft1() {
        return (Number)getAttributeInternal(DRAFT1);
    }

    /**
     * Sets <code>value</code> as attribute value for DRAFT1 using the alias name Draft1.
     * @param value value to set the DRAFT1
     */
    public void setDraft1(Number value) {
        setAttributeInternal(DRAFT1, value);
    }

    /**
     * Gets the attribute value for DRAFT2 using the alias name Draft2.
     * @return the DRAFT2
     */
    public Number getDraft2() {
        return (Number)getAttributeInternal(DRAFT2);
    }

    /**
     * Sets <code>value</code> as attribute value for DRAFT2 using the alias name Draft2.
     * @param value value to set the DRAFT2
     */
    public void setDraft2(Number value) {
        setAttributeInternal(DRAFT2, value);
    }

    /**
     * Gets the attribute value for SLUB_CODE using the alias name SlubCode.
     * @return the SLUB_CODE
     */
    public String getSlubCode() {
        return (String) getAttributeInternal(SLUBCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SLUB_CODE using the alias name SlubCode.
     * @param value value to set the SLUB_CODE
     */
    public void setSlubCode(String value) {
        setAttributeInternal(SLUBCODE, value);
    }

    /**
     * Gets the attribute value for FANCY_YARN_TYPE using the alias name FancyYarnType.
     * @return the FANCY_YARN_TYPE
     */
    public String getFancyYarnType() {
        return (String)getAttributeInternal(FANCYYARNTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for FANCY_YARN_TYPE using the alias name FancyYarnType.
     * @param value value to set the FANCY_YARN_TYPE
     */
    public void setFancyYarnType(String value) {
        setAttributeInternal(FANCYYARNTYPE, value);
    }

    /**
     * Gets the attribute value for TOT_DENIER_RATIO using the alias name TotDenierRatio.
     * @return the TOT_DENIER_RATIO
     */
    public Number getTotDenierRatio() {
        return (Number)getAttributeInternal(TOTDENIERRATIO);
    }

    /**
     * Sets <code>value</code> as attribute value for TOT_DENIER_RATIO using the alias name TotDenierRatio.
     * @param value value to set the TOT_DENIER_RATIO
     */
    public void setTotDenierRatio(Number value) {
        setAttributeInternal(TOTDENIERRATIO, value);
    }


    /**
     * Gets the attribute value for the calculated attribute WarpGSM.
     * @return the WarpGSM
     */
    public Double getWarpGSM() {
        return (Double)getAttributeInternal(WARPGSM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WarpGSM.
     * @param value value to set the  WarpGSM
     */
    public void setWarpGSM(Double value) {
        setAttributeInternal(WARPGSM, value);
    }


    /**
     * Gets the attribute value for CONVERTED_YARN_COUNT using the alias name ConvertedYarnCount.
     * @return the CONVERTED_YARN_COUNT
     */
    public Number getConvertedYarnCount() {
        return (Number)getAttributeInternal(CONVERTEDYARNCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONVERTED_YARN_COUNT using the alias name ConvertedYarnCount.
     * @param value value to set the CONVERTED_YARN_COUNT
     */
    public void setConvertedYarnCount(Number value) {
        setAttributeInternal(CONVERTEDYARNCOUNT, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link XxpmItemMasterWvView.
     */
    public Row getXxpmItemMasterWvView() {
        return (Row)getAttributeInternal(XXPMITEMMASTERWVVIEW);
    }

    /**
     * Sets the master-detail link XxpmItemMasterWvView between this object and <code>value</code>.
     */
    public void setXxpmItemMasterWvView(Row value) {
        setAttributeInternal(XXPMITEMMASTERWVVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SpinningItemDescLov.
     */
    public RowSet getSpinningItemDescLov() {
        return (RowSet)getAttributeInternal(SPINNINGITEMDESCLOV);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    ModelActions ma = new ModelActions();
}
