package ncl.pm.model.bc.vo;

import ncl.pm.model.bc.eo.XxpmItemMasterImpl;

import ncl.pm.model.bc.vo.common.XxpmItemMasterPrnViewRow;

import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 03 15:54:10 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmItemMasterPrnViewRowImpl extends ViewRowImpl implements XxpmItemMasterPrnViewRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Segment1 {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getSegment1();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setSegment1((String)value);
            }
        }
        ,
        Segment2 {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getSegment2();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setSegment2((String)value);
            }
        }
        ,
        Segment3 {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getSegment3();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setSegment3((String)value);
            }
        }
        ,
        Segment4 {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getSegment4();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setSegment4((String)value);
            }
        }
        ,
        Segment5 {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getSegment5();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setSegment5((String)value);
            }
        }
        ,
        Segment6 {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getSegment6();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setSegment6((String)value);
            }
        }
        ,
        Segment7 {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getSegment7();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setSegment7((String)value);
            }
        }
        ,
        ImId {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getImId();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setImId((DBSequence)value);
            }
        }
        ,
        Description {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getDescription();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        FinishType {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getFinishType();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setFinishType((String)value);
            }
        }
        ,
        Category {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getCategory();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setCategory((String)value);
            }
        }
        ,
        BaseDye {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getBaseDye();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setBaseDye((String)value);
            }
        }
        ,
        BaseImId {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getBaseImId();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setBaseImId((Number)value);
            }
        }
        ,
        EngravedNum {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getEngravedNum();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setEngravedNum((String)value);
            }
        }
        ,
        WeavingDescription {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getWeavingDescription();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setWeavingDescription((String)value);
            }
        }
        ,
        WeavingImId {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getWeavingImId();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setWeavingImId((DBSequence)value);
            }
        }
        ,
        ItemStatusFlag {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getItemStatusFlag();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setItemStatusFlag((Integer)value);
            }
        }
        ,
        PrnColor {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getPrnColor();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setPrnColor((String)value);
            }
        }
        ,
        PrnFinishWidthDesc {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getPrnFinishWidthDesc();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setPrnFinishWidthDesc((String)value);
            }
        }
        ,
        PrnFinishTypeDesc {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getPrnFinishTypeDesc();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setPrnFinishTypeDesc((String)value);
            }
        }
        ,
        PrnCategoryDesc {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getPrnCategoryDesc();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setPrnCategoryDesc((String)value);
            }
        }
        ,
        TransWeavingDesc {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getTransWeavingDesc();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setTransWeavingDesc((String)value);
            }
        }
        ,
        PrintingResultant {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getPrintingResultant();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setPrintingResultant((String)value);
            }
        }
        ,
        RowStatus {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getRowStatus();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setRowStatus((Integer)value);
            }
        }
        ,
        Segment3Value {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getSegment3Value();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setSegment3Value((String)value);
            }
        }
        ,
        ItemColorsLov {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getItemColorsLov();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrnFinishTypeLov {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getPrnFinishTypeLov();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrnCategoryLov {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getPrnCategoryLov();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PrnBaseDyeLov {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getPrnBaseDyeLov();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WeavingItemDescLov {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getWeavingItemDescLov();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItemSizeLov {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getItemSizeLov();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItemStatusLov {
            public Object get(XxpmItemMasterPrnViewRowImpl obj) {
                return obj.getItemStatusLov();
            }

            public void put(XxpmItemMasterPrnViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxpmItemMasterPrnViewRowImpl object);

        public abstract void put(XxpmItemMasterPrnViewRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SEGMENT1 = AttributesEnum.Segment1.index();
    public static final int SEGMENT2 = AttributesEnum.Segment2.index();
    public static final int SEGMENT3 = AttributesEnum.Segment3.index();
    public static final int SEGMENT4 = AttributesEnum.Segment4.index();
    public static final int SEGMENT5 = AttributesEnum.Segment5.index();
    public static final int SEGMENT6 = AttributesEnum.Segment6.index();
    public static final int SEGMENT7 = AttributesEnum.Segment7.index();
    public static final int IMID = AttributesEnum.ImId.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int FINISHTYPE = AttributesEnum.FinishType.index();
    public static final int CATEGORY = AttributesEnum.Category.index();
    public static final int BASEDYE = AttributesEnum.BaseDye.index();
    public static final int BASEIMID = AttributesEnum.BaseImId.index();
    public static final int ENGRAVEDNUM = AttributesEnum.EngravedNum.index();
    public static final int WEAVINGDESCRIPTION = AttributesEnum.WeavingDescription.index();
    public static final int WEAVINGIMID = AttributesEnum.WeavingImId.index();
    public static final int ITEMSTATUSFLAG = AttributesEnum.ItemStatusFlag.index();
    public static final int PRNCOLOR = AttributesEnum.PrnColor.index();
    public static final int PRNFINISHWIDTHDESC = AttributesEnum.PrnFinishWidthDesc.index();
    public static final int PRNFINISHTYPEDESC = AttributesEnum.PrnFinishTypeDesc.index();
    public static final int PRNCATEGORYDESC = AttributesEnum.PrnCategoryDesc.index();
    public static final int TRANSWEAVINGDESC = AttributesEnum.TransWeavingDesc.index();
    public static final int PRINTINGRESULTANT = AttributesEnum.PrintingResultant.index();
    public static final int ROWSTATUS = AttributesEnum.RowStatus.index();
    public static final int SEGMENT3VALUE = AttributesEnum.Segment3Value.index();
    public static final int ITEMCOLORSLOV = AttributesEnum.ItemColorsLov.index();
    public static final int PRNFINISHTYPELOV = AttributesEnum.PrnFinishTypeLov.index();
    public static final int PRNCATEGORYLOV = AttributesEnum.PrnCategoryLov.index();
    public static final int PRNBASEDYELOV = AttributesEnum.PrnBaseDyeLov.index();
    public static final int WEAVINGITEMDESCLOV = AttributesEnum.WeavingItemDescLov.index();
    public static final int ITEMSIZELOV = AttributesEnum.ItemSizeLov.index();
    public static final int ITEMSTATUSLOV = AttributesEnum.ItemStatusLov.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxpmItemMasterPrnViewRowImpl() {
    }

    /**
     * Gets XxpmItemMaster entity object.
     * @return the XxpmItemMaster
     */
    public XxpmItemMasterImpl getXxpmItemMaster() {
        return (XxpmItemMasterImpl)getEntity(0);
    }

    /**
     * Gets XxpmWeavingItemMaster entity object.
     * @return the XxpmWeavingItemMaster
     */
    public XxpmItemMasterImpl getXxpmWeavingItemMaster() {
        return (XxpmItemMasterImpl)getEntity(1);
    }

    /**
     * Gets the attribute value for SEGMENT1 using the alias name Segment1.
     * @return the SEGMENT1
     */
    public String getSegment1() {
        return (String)getAttributeInternal(SEGMENT1);
    }

    /**
     * Sets <code>value</code> as attribute value for SEGMENT1 using the alias name Segment1.
     * @param value value to set the SEGMENT1
     */
    public void setSegment1(String value) {
        setAttributeInternal(SEGMENT1, value);
    }

    /**
     * Gets the attribute value for SEGMENT2 using the alias name Segment2.
     * @return the SEGMENT2
     */
    public String getSegment2() {
        return (String)getAttributeInternal(SEGMENT2);
    }

    /**
     * Sets <code>value</code> as attribute value for SEGMENT2 using the alias name Segment2.
     * @param value value to set the SEGMENT2
     */
    public void setSegment2(String value) {
        setAttributeInternal(SEGMENT2, value);
    }

    /**
     * Gets the attribute value for SEGMENT3 using the alias name Segment3.
     * @return the SEGMENT3
     */
    public String getSegment3() {
        return (String)getAttributeInternal(SEGMENT3);
    }

    /**
     * Sets <code>value</code> as attribute value for SEGMENT3 using the alias name Segment3.
     * @param value value to set the SEGMENT3
     */
    public void setSegment3(String value) {
        setAttributeInternal(SEGMENT3, value);
    }

    /**
     * Gets the attribute value for SEGMENT4 using the alias name Segment4.
     * @return the SEGMENT4
     */
    public String getSegment4() {
        return (String)getAttributeInternal(SEGMENT4);
    }

    /**
     * Sets <code>value</code> as attribute value for SEGMENT4 using the alias name Segment4.
     * @param value value to set the SEGMENT4
     */
    public void setSegment4(String value) {
        setAttributeInternal(SEGMENT4, value);
    }

    /**
     * Gets the attribute value for SEGMENT5 using the alias name Segment5.
     * @return the SEGMENT5
     */
    public String getSegment5() {
        return (String)getAttributeInternal(SEGMENT5);
    }

    /**
     * Sets <code>value</code> as attribute value for SEGMENT5 using the alias name Segment5.
     * @param value value to set the SEGMENT5
     */
    public void setSegment5(String value) {
        setAttributeInternal(SEGMENT5, value);
    }

    /**
     * Gets the attribute value for SEGMENT6 using the alias name Segment6.
     * @return the SEGMENT6
     */
    public String getSegment6() {
        return (String)getAttributeInternal(SEGMENT6);
    }

    /**
     * Sets <code>value</code> as attribute value for SEGMENT6 using the alias name Segment6.
     * @param value value to set the SEGMENT6
     */
    public void setSegment6(String value) {
        setAttributeInternal(SEGMENT6, value);
    }

    /**
     * Gets the attribute value for SEGMENT7 using the alias name Segment7.
     * @return the SEGMENT7
     */
    public String getSegment7() {
        return (String)getAttributeInternal(SEGMENT7);
    }

    /**
     * Sets <code>value</code> as attribute value for SEGMENT7 using the alias name Segment7.
     * @param value value to set the SEGMENT7
     */
    public void setSegment7(String value) {
        setAttributeInternal(SEGMENT7, value);
    }

    /**
     * Gets the attribute value for IM_ID using the alias name ImId.
     * @return the IM_ID
     */
    public DBSequence getImId() {
        return (DBSequence)getAttributeInternal(IMID);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_ID using the alias name ImId.
     * @param value value to set the IM_ID
     */
    public void setImId(DBSequence value) {
        setAttributeInternal(IMID, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for FINISH_TYPE using the alias name FinishType.
     * @return the FINISH_TYPE
     */
    public String getFinishType() {
        return (String)getAttributeInternal(FINISHTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for FINISH_TYPE using the alias name FinishType.
     * @param value value to set the FINISH_TYPE
     */
    public void setFinishType(String value) {
        setAttributeInternal(FINISHTYPE, value);
    }

    /**
     * Gets the attribute value for CATEGORY using the alias name Category.
     * @return the CATEGORY
     */
    public String getCategory() {
        return (String)getAttributeInternal(CATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for CATEGORY using the alias name Category.
     * @param value value to set the CATEGORY
     */
    public void setCategory(String value) {
        setAttributeInternal(CATEGORY, value);
    }

    /**
     * Gets the attribute value for BASE_DYE using the alias name BaseDye.
     * @return the BASE_DYE
     */
    public String getBaseDye() {
        return (String)getAttributeInternal(BASEDYE);
    }

    /**
     * Sets <code>value</code> as attribute value for BASE_DYE using the alias name BaseDye.
     * @param value value to set the BASE_DYE
     */
    public void setBaseDye(String value) {
        setAttributeInternal(BASEDYE, value);
    }

    /**
     * Gets the attribute value for BASE_IM_ID using the alias name BaseImId.
     * @return the BASE_IM_ID
     */
    public Number getBaseImId() {
        return (Number)getAttributeInternal(BASEIMID);
    }

    /**
     * Sets <code>value</code> as attribute value for BASE_IM_ID using the alias name BaseImId.
     * @param value value to set the BASE_IM_ID
     */
    public void setBaseImId(Number value) {
        setAttributeInternal(BASEIMID, value);
    }

    /**
     * Gets the attribute value for ENGRAVED_NUM using the alias name EngravedNum.
     * @return the ENGRAVED_NUM
     */
    public String getEngravedNum() {
        return (String)getAttributeInternal(ENGRAVEDNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for ENGRAVED_NUM using the alias name EngravedNum.
     * @param value value to set the ENGRAVED_NUM
     */
    public void setEngravedNum(String value) {
        setAttributeInternal(ENGRAVEDNUM, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name WeavingDescription.
     * @return the DESCRIPTION
     */
    public String getWeavingDescription() {
        return (String)getAttributeInternal(WEAVINGDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name WeavingDescription.
     * @param value value to set the DESCRIPTION
     */
    public void setWeavingDescription(String value) {
        setAttributeInternal(WEAVINGDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for IM_ID using the alias name WeavingImId.
     * @return the IM_ID
     */
    public DBSequence getWeavingImId() {
        return (DBSequence)getAttributeInternal(WEAVINGIMID);
    }

    /**
     * Sets <code>value</code> as attribute value for IM_ID using the alias name WeavingImId.
     * @param value value to set the IM_ID
     */
    public void setWeavingImId(DBSequence value) {
        setAttributeInternal(WEAVINGIMID, value);
    }

    /**
     * Gets the attribute value for ITEM_STATUS_FLAG using the alias name ItemStatusFlag.
     * @return the ITEM_STATUS_FLAG
     */
    public Integer getItemStatusFlag() {
        return (Integer)getAttributeInternal(ITEMSTATUSFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_STATUS_FLAG using the alias name ItemStatusFlag.
     * @param value value to set the ITEM_STATUS_FLAG
     */
    public void setItemStatusFlag(Integer value) {
        setAttributeInternal(ITEMSTATUSFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrnColor.
     * @return the PrnColor
     */
    public String getPrnColor() {
        return (String)getAttributeInternal(PRNCOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrnColor.
     * @param value value to set the  PrnColor
     */
    public void setPrnColor(String value) {
        setAttributeInternal(PRNCOLOR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrnFinishWidthDesc.
     * @return the PrnFinishWidthDesc
     */
    public String getPrnFinishWidthDesc() {
        return (String)getAttributeInternal(PRNFINISHWIDTHDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrnFinishWidthDesc.
     * @param value value to set the  PrnFinishWidthDesc
     */
    public void setPrnFinishWidthDesc(String value) {
        setAttributeInternal(PRNFINISHWIDTHDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrnFinishTypeDesc.
     * @return the PrnFinishTypeDesc
     */
    public String getPrnFinishTypeDesc() {
        return (String)getAttributeInternal(PRNFINISHTYPEDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrnFinishTypeDesc.
     * @param value value to set the  PrnFinishTypeDesc
     */
    public void setPrnFinishTypeDesc(String value) {
        setAttributeInternal(PRNFINISHTYPEDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrnCategoryDesc.
     * @return the PrnCategoryDesc
     */
    public String getPrnCategoryDesc() {
        return (String)getAttributeInternal(PRNCATEGORYDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrnCategoryDesc.
     * @param value value to set the  PrnCategoryDesc
     */
    public void setPrnCategoryDesc(String value) {
        setAttributeInternal(PRNCATEGORYDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransWeavingDesc.
     * @return the TransWeavingDesc
     */
    public String getTransWeavingDesc() {
        return (String)getAttributeInternal(TRANSWEAVINGDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransWeavingDesc.
     * @param value value to set the  TransWeavingDesc
     */
    public void setTransWeavingDesc(String value) {
        setAttributeInternal(TRANSWEAVINGDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PrintingResultant.
     * @return the PrintingResultant
     */
    public String getPrintingResultant() {
        return (String)getAttributeInternal(PRINTINGRESULTANT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PrintingResultant.
     * @param value value to set the  PrintingResultant
     */
    public void setPrintingResultant(String value) {
        setAttributeInternal(PRINTINGRESULTANT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RowStatus.
     * @return the RowStatus
     */
    public Integer getRowStatus() {
        //return (Integer) getAttributeInternal(ROWSTATUS);
        byte entityState = this.getEntity(0).getEntityState();
        return new Integer(entityState);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RowStatus.
     * @param value value to set the  RowStatus
     */
    public void setRowStatus(Integer value) {
        setAttributeInternal(ROWSTATUS, value);
    }


    /**
     * Gets the attribute value for SEGMENT3VALUE using the alias name Segment3Value.
     * @return the SEGMENT3VALUE
     */
    public String getSegment3Value() {
        return (String) getAttributeInternal(SEGMENT3VALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for SEGMENT3VALUE using the alias name Segment3Value.
     * @param value value to set the SEGMENT3VALUE
     */
    public void setSegment3Value(String value) {
        setAttributeInternal(SEGMENT3VALUE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemColorsLov.
     */
    public RowSet getItemColorsLov() {
        return (RowSet)getAttributeInternal(ITEMCOLORSLOV);
    }


    /**
     * Gets the view accessor <code>RowSet</code> PrnFinishTypeLov.
     */
    public RowSet getPrnFinishTypeLov() {
        return (RowSet)getAttributeInternal(PRNFINISHTYPELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PrnCategoryLov.
     */
    public RowSet getPrnCategoryLov() {
        return (RowSet)getAttributeInternal(PRNCATEGORYLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PrnBaseDyeLov.
     */
    public RowSet getPrnBaseDyeLov() {
        return (RowSet)getAttributeInternal(PRNBASEDYELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WeavingItemDescLov.
     */
    public RowSet getWeavingItemDescLov() {
        return (RowSet)getAttributeInternal(WEAVINGITEMDESCLOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemSizeLov.
     */
    public RowSet getItemSizeLov() {
        return (RowSet)getAttributeInternal(ITEMSIZELOV);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemStatusLov.
     */
    public RowSet getItemStatusLov() {
        return (RowSet)getAttributeInternal(ITEMSTATUSLOV);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
    
    public void updatePrnLovsAccessor(){
        getItemColorsLov().executeQuery();
        getPrnCategoryLov().executeQuery();
        getItemSizeLov().executeQuery();
        getPrnFinishTypeLov().executeQuery();
    }
}
