package ncl.pm.model.bc.vo;

import java.sql.ResultSet;

import ncl.pm.model.bc.view.xxpmJC.ModelActions;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;

import utils.system;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 19 19:50:50 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmSetBomViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxpmSetBomViewImpl() {
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);

        if (value != null) {
            value.setAttribute("ConcatenatedSegments",
                               ma.getItemConcateSegments(this.getDBTransaction(),
                                                         (Integer)value.getAttribute("SetId"),
                                                         "24", "31"));
//            Integer progId = (Integer)value.getAttribute("ProgId");
            //            value.setAttribute("ProgramName",
            //                               ma.getProgramName(this.getDBTransaction(),
            //                                                 progId));
//            String id = value.getAttribute("CustomerId").toString();
//            ViewObject vo =
//                this.getApplicationModule().findViewObject("CustomersLov");
//            String where1 = "CUSTOMER_ID = " + id;
//            String where2 = "1 = 1";
//            vo.setWhereClause(where1);
//            vo.executeQuery();
//            for (int i = 0; i < vo.getEstimatedRowCount(); i++) {
//                Row curRow = vo.getRowAtRangeIndex(i);
//                if (curRow != null) {
//                    value.setAttribute("CustomerNameTrans",
//                                       curRow.getAttribute("CustomerName"));
//
//                }
//            }
//            vo.setWhereClause(where2);
        }
        return value;
    }


    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }
    ModelActions ma = new ModelActions();

    /**
     * Returns the variable value for BindBomNum.
     * @return variable value for BindBomNum
     */
    public String getBindBomNum() {
        return (String)ensureVariableManager().getVariableValue("BindBomNum");
    }

    /**
     * Sets <code>value</code> for variable BindBomNum.
     * @param value value to bind as BindBomNum
     */
    public void setBindBomNum(String value) {
        ensureVariableManager().setVariableValue("BindBomNum", value);
    }
}
