package ncl.pm.model.bc.vo;

import java.sql.ResultSet;

import oracle.jbo.Row;
import oracle.jbo.server.RowQualifier;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 26 11:23:41 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmArticleBomFabricViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxpmArticleBomFabricViewImpl() {
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        if (value != null) {
            Object id = value.getAttribute("ImId");
            ViewObjectImpl fabVo =
                (ViewObjectImpl)this.getApplicationModule().findViewObject("ArticleBomFablov");
            RowQualifier rq = new RowQualifier("ImId = " + id);
            Row[] fabRows = fabVo.getFilteredRows(rq);
            for (int i = 0; i < fabRows.length; i++) {
                Row curRow = fabRows[i];
                value.setAttribute("Description",
                                   curRow.getAttribute("Description"));
                value.setAttribute("ItemColor",
                                   curRow.getAttribute("ItemColor"));
                value.setAttribute("ItemSize",
                                   curRow.getAttribute("ItemSize"));
                value.setAttribute("Uom", curRow.getAttribute("Uom"));
            }
        }
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }

    public void insertRow(Row row) {
        /*         Row lastRow = this.last();
        if (lastRow != null) {
            int indx = this.getRangeIndexOf(lastRow) + 1;
            this.insertRowAtRangeIndex(indx, row);
            this.setCurrentRow(row);
        } else
            super.insertRow(row); */
        this.insertRowAtRangeIndex(0, row);
        this.setCurrentRow(row);
    }
}
