package ncl.pm.model.bc.vo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 01 16:55:37 PKT 2016
// ---------------------------------------------------------------------
public interface XxpmMadeupProgramsViewRow extends Row {
    void updateMadeupProgLovsAccessor();
}
