package ncl.pm.model.bc.vo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 25 19:58:42 PKT 2016
// ---------------------------------------------------------------------
public interface XxpmPoHeaderViewRow extends Row {
    void updatePoHeaderLovsAccessor();
}
