package ncl.pm.model.bc.vo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 18 13:07:02 PKT 2016
// ---------------------------------------------------------------------
public interface XxpmItemMasterAccViewRow extends Row {
    void updateAccLovsAccessor();
}
