package ncl.pm.model.bc.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 11 12:47:40 PKT 2016
// ---------------------------------------------------------------------
public interface XxpmYarnBlendView extends ViewObject {
    void revertOrremoveCurRowValue();
}
