package ncl.pm.model.bc.vo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 13 16:19:08 PKT 2016
// ---------------------------------------------------------------------
public interface XxpmItemMasterPrnViewRow extends Row {
    void updatePrnLovsAccessor();
}
