package ncl.pm.model.bc.vo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 01 17:09:00 PKT 2016
// ---------------------------------------------------------------------
public interface XxpmMadeupArticlesViewRow extends Row {
    void updateMadeupArticleLovsAccessor();
}
