package ncl.pm.model.bc.vo.client;

import ncl.pm.model.bc.vo.common.XxpmYarnTypeViewRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 01 17:59:46 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmYarnTypeViewRowClient extends RowImpl implements XxpmYarnTypeViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public XxpmYarnTypeViewRowClient() {
    }

    public void updateYtLovsAccessor() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"updateYtLovsAccessor",null,null);
        return;
    }
}
