package ncl.pm.model.bc.vo.client;

import ncl.pm.model.bc.vo.common.XxpmItemMasterAccViewRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 18 13:07:02 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmItemMasterAccViewRowClient extends RowImpl implements XxpmItemMasterAccViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public XxpmItemMasterAccViewRowClient() {
    }

    public void updateAccLovsAccessor() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"updateAccLovsAccessor",null,null);
        return;
    }
}
