package ncl.pm.model.bc.vo.client;

import ncl.pm.model.bc.vo.common.XxpmYarnBlendViewRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 01 17:55:57 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmYarnBlendViewRowClient extends RowImpl implements XxpmYarnBlendViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public XxpmYarnBlendViewRowClient() {
    }

    public void updateYbLovsAccessor() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"updateYbLovsAccessor",null,null);
        return;
    }
}
