package ncl.pm.model.bc.vo.client;

import ncl.pm.model.bc.vo.common.XxpmPoHeaderViewRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 25 19:58:42 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmPoHeaderViewRowClient extends RowImpl implements XxpmPoHeaderViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public XxpmPoHeaderViewRowClient() {
    }

    public void updatePoHeaderLovsAccessor() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"updatePoHeaderLovsAccessor",null,null);
        return;
    }
}
