package ncl.pm.model.bc.vo.client;

import ncl.pm.model.bc.vo.common.XxpmYarnBlendView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 11 12:47:40 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmYarnBlendViewClient extends ViewUsageImpl implements XxpmYarnBlendView {
    /**
     * This is the default constructor (do not remove).
     */
    public XxpmYarnBlendViewClient() {
    }

    public void revertOrremoveCurRowValue() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"revertOrremoveCurRowValue",null,null);
        return;
    }
}
