package ncl.pm.model.bc.vo.client;

import ncl.pm.model.bc.vo.common.XxpmPoLinesViewRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 14 17:57:38 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmPoLinesViewRowClient extends RowImpl implements XxpmPoLinesViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public XxpmPoLinesViewRowClient() {
    }

    public Integer getDefaultValForVendorSiteId() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getDefaultValForVendorSiteId",null,null);
        return (Integer)_ret;
    }
}
