package ncl.pm.model.bc.vo.client;

import ncl.pm.model.bc.vo.common.XxpmMadeupProgramsViewRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 01 16:55:37 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmMadeupProgramsViewRowClient extends RowImpl implements XxpmMadeupProgramsViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public XxpmMadeupProgramsViewRowClient() {
    }

    public void updateMadeupProgLovsAccessor() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"updateMadeupProgLovsAccessor",null,null);
        return;
    }
}
