package ncl.pm.model.bc.vo.lov;

import ncl.pm.model.bc.generic.GenericViewObjectImpl;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 26 18:25:50 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ArticleBomAcclovImpl extends GenericViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ArticleBomAcclovImpl() {
    }

    /**
     * Returns the variable value for BindProgId.
     * @return variable value for BindProgId
     */
    public Integer getBindProgId() {
        return (Integer)ensureVariableManager().getVariableValue("BindProgId");
    }

    /**
     * Sets <code>value</code> for variable BindProgId.
     * @param value value to bind as BindProgId
     */
    public void setBindProgId(Integer value) {
        ensureVariableManager().setVariableValue("BindProgId", value);
    }
}
