package ncl.pm.model.bc.vo.lov;

import java.sql.ResultSet;

import ncl.pm.model.bc.generic.GenericViewObjectImpl;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 13 18:25:37 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ItemSizeLovImpl extends GenericViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ItemSizeLovImpl() {
    }


    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }

    /**
     * Returns the bind variable value for BindModule1.
     * @return bind variable value for BindModule1
     */
    public String getBindModule1() {
        return (String)getNamedWhereClauseParam("BindModule1");
    }

    /**
     * Sets <code>value</code> for bind variable BindModule1.
     * @param value value to bind as BindModule1
     */
    public void setBindModule1(String value) {
        setNamedWhereClauseParam("BindModule1", value);
    }

    /**
     * Returns the bind variable value for BindModule2.
     * @return bind variable value for BindModule2
     */
    public String getBindModule2() {
        return (String)getNamedWhereClauseParam("BindModule2");
    }

    /**
     * Sets <code>value</code> for bind variable BindModule2.
     * @param value value to bind as BindModule2
     */
    public void setBindModule2(String value) {
        setNamedWhereClauseParam("BindModule2", value);
    }
}
