package ncl.pm.model.bc.vo.lov;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 22 19:22:27 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MadeupProgDetailsLovRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ProgId {
            public Object get(MadeupProgDetailsLovRowImpl obj) {
                return obj.getProgId();
            }

            public void put(MadeupProgDetailsLovRowImpl obj, Object value) {
                obj.setProgId((Integer)value);
            }
        }
        ,
        ProgName {
            public Object get(MadeupProgDetailsLovRowImpl obj) {
                return obj.getProgName();
            }

            public void put(MadeupProgDetailsLovRowImpl obj, Object value) {
                obj.setProgName((String)value);
            }
        }
        ,
        CustomerName {
            public Object get(MadeupProgDetailsLovRowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(MadeupProgDetailsLovRowImpl obj, Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        ProgManager {
            public Object get(MadeupProgDetailsLovRowImpl obj) {
                return obj.getProgManager();
            }

            public void put(MadeupProgDetailsLovRowImpl obj, Object value) {
                obj.setProgManager((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(MadeupProgDetailsLovRowImpl object);

        public abstract void put(MadeupProgDetailsLovRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PROGID = AttributesEnum.ProgId.index();
    public static final int PROGNAME = AttributesEnum.ProgName.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int PROGMANAGER = AttributesEnum.ProgManager.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MadeupProgDetailsLovRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ProgId.
     * @return the ProgId
     */
    public Integer getProgId() {
        return (Integer) getAttributeInternal(PROGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProgId.
     * @param value value to set the  ProgId
     */
    public void setProgId(Integer value) {
        setAttributeInternal(PROGID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProgName.
     * @return the ProgName
     */
    public String getProgName() {
        return (String) getAttributeInternal(PROGNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProgName.
     * @param value value to set the  ProgName
     */
    public void setProgName(String value) {
        setAttributeInternal(PROGNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName.
     * @param value value to set the  CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProgManager.
     * @return the ProgManager
     */
    public String getProgManager() {
        return (String) getAttributeInternal(PROGMANAGER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProgManager.
     * @param value value to set the  ProgManager
     */
    public void setProgManager(String value) {
        setAttributeInternal(PROGMANAGER, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
