package ncl.pm.model.bc.vo.lov;

import java.sql.ResultSet;

import ncl.pm.model.bc.generic.GenericViewObjectImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 02 10:53:04 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProgSizesLovImpl extends GenericViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ProgSizesLovImpl() {
    }

    /**
     * Returns the bind variable value for BindProgId.
     * @return bind variable value for BindProgId
     */
    public Number getBindProgId() {
        return (Number)getNamedWhereClauseParam("BindProgId");
    }

    /**
     * Sets <code>value</code> for bind variable BindProgId.
     * @param value value to bind as BindProgId
     */
    public void setBindProgId(Number value) {
        setNamedWhereClauseParam("BindProgId", value);
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params,
                                             int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc,
                                                 ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }
}
