package ncl.pm.model.bc.eo;

import ncl.pm.model.bc.view.xxpmJC.ModelActions;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.DMLConstraintException;
import oracle.jbo.DMLException;
import oracle.jbo.Key;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 04 11:28:16 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmSetBomAccessoriesImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AccessoryId {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getAccessoryId();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setAccessoryId((DBSequence)value);
            }
        },
        SetBomId {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getSetBomId();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setSetBomId((Number)value);
            }
        },
        ImId {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getImId();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setImId((Number)value);
            }
        },
        SubInventory {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getSubInventory();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setSubInventory((String)value);
            }
        },
        Consumption {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getConsumption();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setConsumption((Number)value);
            }
        },
        Wastage {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getWastage();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setWastage((Number)value);
            }
        },
        AccColor {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getAccColor();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setAccColor((String)value);
            }
        },
        AccSize {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getAccSize();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setAccSize((String)value);
            }
        },
        CreatedBy {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        },
        CreationDate {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        },
        LastUpdatedBy {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        },
        LastUpdateDate {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        },
        RespId {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getRespId();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setRespId((String)value);
            }
        },
        Active {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getActive();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setActive((Integer)value);
            }
        },
        EbsStatus {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getEbsStatus();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setEbsStatus((Integer)value);
            }
        },
        XxpmSetBom {
            public Object get(XxpmSetBomAccessoriesImpl obj) {
                return obj.getXxpmSetBom();
            }

            public void put(XxpmSetBomAccessoriesImpl obj, Object value) {
                obj.setXxpmSetBom((XxpmSetBomImpl)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxpmSetBomAccessoriesImpl object);

        public abstract void put(XxpmSetBomAccessoriesImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ACCESSORYID = AttributesEnum.AccessoryId.index();
    public static final int SETBOMID = AttributesEnum.SetBomId.index();
    public static final int IMID = AttributesEnum.ImId.index();
    public static final int SUBINVENTORY = AttributesEnum.SubInventory.index();
    public static final int CONSUMPTION = AttributesEnum.Consumption.index();
    public static final int WASTAGE = AttributesEnum.Wastage.index();
    public static final int ACCCOLOR = AttributesEnum.AccColor.index();
    public static final int ACCSIZE = AttributesEnum.AccSize.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE =
        AttributesEnum.LastUpdateDate.index();
    public static final int RESPID = AttributesEnum.RespId.index();
    public static final int ACTIVE = AttributesEnum.Active.index();
    public static final int EBSSTATUS = AttributesEnum.EbsStatus.index();
    public static final int XXPMSETBOM = AttributesEnum.XxpmSetBom.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxpmSetBomAccessoriesImpl() {
    }

    /**
     * Gets the attribute value for AccessoryId, using the alias name AccessoryId.
     * @return the AccessoryId
     */
    public DBSequence getAccessoryId() {
        return (DBSequence)getAttributeInternal(ACCESSORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccessoryId.
     * @param value value to set the AccessoryId
     */
    public void setAccessoryId(DBSequence value) {
        setAttributeInternal(ACCESSORYID, value);
    }

    /**
     * Gets the attribute value for SetBomId, using the alias name SetBomId.
     * @return the SetBomId
     */
    public Number getSetBomId() {
        return (Number)getAttributeInternal(SETBOMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SetBomId.
     * @param value value to set the SetBomId
     */
    public void setSetBomId(Number value) {
        setAttributeInternal(SETBOMID, value);
    }

    /**
     * Gets the attribute value for ImId, using the alias name ImId.
     * @return the ImId
     */
    public Number getImId() {
        return (Number)getAttributeInternal(IMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImId.
     * @param value value to set the ImId
     */
    public void setImId(Number value) {
        setAttributeInternal(IMID, value);
    }

    /**
     * Gets the attribute value for SubInventory, using the alias name SubInventory.
     * @return the SubInventory
     */
    public String getSubInventory() {
        return (String)getAttributeInternal(SUBINVENTORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubInventory.
     * @param value value to set the SubInventory
     */
    public void setSubInventory(String value) {
        setAttributeInternal(SUBINVENTORY, value);
    }

    /**
     * Gets the attribute value for Consumption, using the alias name Consumption.
     * @return the Consumption
     */
    public Number getConsumption() {
        return (Number)getAttributeInternal(CONSUMPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Consumption.
     * @param value value to set the Consumption
     */
    public void setConsumption(Number value) {
        setAttributeInternal(CONSUMPTION, value);
    }

    /**
     * Gets the attribute value for Wastage, using the alias name Wastage.
     * @return the Wastage
     */
    public Number getWastage() {
        return (Number)getAttributeInternal(WASTAGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Wastage.
     * @param value value to set the Wastage
     */
    public void setWastage(Number value) {
        setAttributeInternal(WASTAGE, value);
    }

    /**
     * Gets the attribute value for AccColor, using the alias name AccColor.
     * @return the AccColor
     */
    public String getAccColor() {
        return (String)getAttributeInternal(ACCCOLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccColor.
     * @param value value to set the AccColor
     */
    public void setAccColor(String value) {
        setAttributeInternal(ACCCOLOR, value);
    }

    /**
     * Gets the attribute value for AccSize, using the alias name AccSize.
     * @return the AccSize
     */
    public String getAccSize() {
        return (String)getAttributeInternal(ACCSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccSize.
     * @param value value to set the AccSize
     */
    public void setAccSize(String value) {
        setAttributeInternal(ACCSIZE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for RespId, using the alias name RespId.
     * @return the RespId
     */
    public String getRespId() {
        return (String)getAttributeInternal(RESPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RespId.
     * @param value value to set the RespId
     */
    public void setRespId(String value) {
        setAttributeInternal(RESPID, value);
    }

    /**
     * Gets the attribute value for Active, using the alias name Active.
     * @return the Active
     */
    public Integer getActive() {
        return (Integer)getAttributeInternal(ACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Active.
     * @param value value to set the Active
     */
    public void setActive(Integer value) {
        setAttributeInternal(ACTIVE, value);
    }

    /**
     * Gets the attribute value for EbsStatus, using the alias name EbsStatus.
     * @return the EbsStatus
     */
    public Integer getEbsStatus() {
        return (Integer)getAttributeInternal(EBSSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for EbsStatus.
     * @param value value to set the EbsStatus
     */
    public void setEbsStatus(Integer value) {
        setAttributeInternal(EBSSTATUS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity XxpmSetBomImpl.
     */
    public XxpmSetBomImpl getXxpmSetBom() {
        return (XxpmSetBomImpl)getAttributeInternal(XXPMSETBOM);
    }

    /**
     * Sets <code>value</code> as the associated entity XxpmSetBomImpl.
     */
    public void setXxpmSetBom(XxpmSetBomImpl value) {
        setAttributeInternal(XXPMSETBOM, value);
    }

    /**
     * @param accessoryId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence accessoryId) {
        return new Key(new Object[] { accessoryId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject =
                    EntityDefImpl.findDefObject("ncl.pm.model.bc.eo.XxpmSetBomAccessories");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        try {
            ADFContext.getCurrent().getSessionScope().put("setBomCreationMsg",
                                                          null);
            super.doDML(operation, e);
            if (operation == DML_INSERT || operation == DML_UPDATE) {
                ADFContext.getCurrent().getSessionScope().put("setBomCreationMsg",
                                                              "Bom has been saved successfully.");
            }
        } catch (DMLConstraintException dce) {
            ma.showError(this.getDBTransaction(),
                         "Constraint: " + dce.getConstraintName() +
                         " voilated.");
            return;

        } catch (DMLException de) {
            String exception = de.getCause().toString();
            String msg =
                exception.substring(exception.indexOf(":", exception.indexOf("ORA")) +
                                    2);
            ma.showError(this.getDBTransaction(),
                         msg.substring(0, msg.indexOf("ORA") > 1 ?
                                          msg.indexOf("ORA") - 1 :
                                          msg.length()));
            return;

        } catch (Exception e1) {
            e1.printStackTrace();
            ma.showError(this.getDBTransaction(),
                         "There is an error in doDML method of XxpmArticleBomImpl. Class: " + e1.getClass());
            return;
        }
    }
    ModelActions ma = new ModelActions();
}
