package ncl.pm.model.bc.eo;

import ncl.pm.model.bc.view.xxpmJC.ModelActions;

import oracle.jbo.AttributeList;
import oracle.jbo.DMLConstraintException;
import oracle.jbo.DMLException;
import oracle.jbo.Key;
import oracle.jbo.RowInconsistentException;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 18 15:09:44 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmWeftImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        WeftId {
            public Object get(XxpmWeftImpl obj) {
                return obj.getWeftId();
            }

            public void put(XxpmWeftImpl obj, Object value) {
                obj.setWeftId((DBSequence)value);
            }
        },
        ImId {
            public Object get(XxpmWeftImpl obj) {
                return obj.getImId();
            }

            public void put(XxpmWeftImpl obj, Object value) {
                obj.setImId((Number)value);
            }
        },
        Segment2 {
            public Object get(XxpmWeftImpl obj) {
                return obj.getSegment2();
            }

            public void put(XxpmWeftImpl obj, Object value) {
                obj.setSegment2((String)value);
            }
        },
        BaseImId {
            public Object get(XxpmWeftImpl obj) {
                return obj.getBaseImId();
            }

            public void put(XxpmWeftImpl obj, Object value) {
                obj.setBaseImId((Number)value);
            }
        },
        XxpmItemMaster {
            public Object get(XxpmWeftImpl obj) {
                return obj.getXxpmItemMaster();
            }

            public void put(XxpmWeftImpl obj, Object value) {
                obj.setXxpmItemMaster((XxpmItemMasterImpl)value);
            }
        },
        XxpmYarnBlendRsltV {
            public Object get(XxpmWeftImpl obj) {
                return obj.getXxpmYarnBlendRsltV();
            }

            public void put(XxpmWeftImpl obj, Object value) {
                obj.setXxpmYarnBlendRsltV((EntityImpl)value);
            }
        },
        XxpmYarnTypeRsltV {
            public Object get(XxpmWeftImpl obj) {
                return obj.getXxpmYarnTypeRsltV();
            }

            public void put(XxpmWeftImpl obj, Object value) {
                obj.setXxpmYarnTypeRsltV((EntityImpl)value);
            }
        },
        XxpmItemMaster1 {
            public Object get(XxpmWeftImpl obj) {
                return obj.getXxpmItemMaster1();
            }

            public void put(XxpmWeftImpl obj, Object value) {
                obj.setXxpmItemMaster1((XxpmItemMasterImpl)value);
            }
        },
        XxpmItemMaster2 {
            public Object get(XxpmWeftImpl obj) {
                return obj.getXxpmItemMaster2();
            }

            public void put(XxpmWeftImpl obj, Object value) {
                obj.setXxpmItemMaster2((XxpmItemMasterImpl)value);
            }
        },
        XxpmItemMaster3 {
            public Object get(XxpmWeftImpl obj) {
                return obj.getXxpmItemMaster3();
            }

            public void put(XxpmWeftImpl obj, Object value) {
                obj.setXxpmItemMaster3((XxpmItemMasterImpl)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxpmWeftImpl object);

        public abstract void put(XxpmWeftImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int WEFTID = AttributesEnum.WeftId.index();
    public static final int IMID = AttributesEnum.ImId.index();
    public static final int SEGMENT2 = AttributesEnum.Segment2.index();
    public static final int BASEIMID = AttributesEnum.BaseImId.index();
    public static final int XXPMITEMMASTER =
        AttributesEnum.XxpmItemMaster.index();
    public static final int XXPMYARNBLENDRSLTV =
        AttributesEnum.XxpmYarnBlendRsltV.index();
    public static final int XXPMYARNTYPERSLTV =
        AttributesEnum.XxpmYarnTypeRsltV.index();
    public static final int XXPMITEMMASTER1 =
        AttributesEnum.XxpmItemMaster1.index();
    public static final int XXPMITEMMASTER2 =
        AttributesEnum.XxpmItemMaster2.index();
    public static final int XXPMITEMMASTER3 =
        AttributesEnum.XxpmItemMaster3.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxpmWeftImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject =
                    EntityDefImpl.findDefObject("ncl.pm.model.bc.eo.XxpmWeft");
        }
        return mDefinitionObject;
    }

    @Override
    public void postChanges(TransactionEvent e) {
        if (this.getPostState() == STATUS_NEW ||
            this.getPostState() == STATUS_MODIFIED) {
            XxpmItemMasterImpl item =
                (XxpmItemMasterImpl)this.getXxpmItemMaster();
            if (item != null) {
                item.postChanges(e);
            }
        }
        super.postChanges(e);
    }

    /**
     * Gets the attribute value for WeftId, using the alias name WeftId.
     * @return the WeftId
     */
    public DBSequence getWeftId() {
        return (DBSequence)getAttributeInternal(WEFTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeftId.
     * @param value value to set the WeftId
     */
    public void setWeftId(DBSequence value) {
        setAttributeInternal(WEFTID, value);
    }

    /**
     * Gets the attribute value for ImId, using the alias name ImId.
     * @return the ImId
     */
    public Number getImId() {
        return (Number)getAttributeInternal(IMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImId.
     * @param value value to set the ImId
     */
    public void setImId(Number value) {
        setAttributeInternal(IMID, value);
    }

    /**
     * Gets the attribute value for Segment2, using the alias name Segment2.
     * @return the Segment2
     */
    public String getSegment2() {
        return (String)getAttributeInternal(SEGMENT2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Segment2.
     * @param value value to set the Segment2
     */
    public void setSegment2(String value) {
        setAttributeInternal(SEGMENT2, value);
    }

    /**
     * Gets the attribute value for BaseImId, using the alias name BaseImId.
     * @return the BaseImId
     */
    public Number getBaseImId() {
        return (Number)getAttributeInternal(BASEIMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BaseImId.
     * @param value value to set the BaseImId
     */
    public void setBaseImId(Number value) {
        setAttributeInternal(BASEIMID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity XxpmItemMasterImpl.
     */
    public XxpmItemMasterImpl getXxpmItemMaster() {
        return (XxpmItemMasterImpl)getAttributeInternal(XXPMITEMMASTER);
    }

    /**
     * Sets <code>value</code> as the associated entity XxpmItemMasterImpl.
     */
    public void setXxpmItemMaster(XxpmItemMasterImpl value) {
        setAttributeInternal(XXPMITEMMASTER, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getXxpmYarnBlendRsltV() {
        return (EntityImpl)getAttributeInternal(XXPMYARNBLENDRSLTV);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setXxpmYarnBlendRsltV(EntityImpl value) {
        setAttributeInternal(XXPMYARNBLENDRSLTV, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getXxpmYarnTypeRsltV() {
        return (EntityImpl)getAttributeInternal(XXPMYARNTYPERSLTV);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setXxpmYarnTypeRsltV(EntityImpl value) {
        setAttributeInternal(XXPMYARNTYPERSLTV, value);
    }

    /**
     * @return the associated entity XxpmItemMasterImpl.
     */
    public XxpmItemMasterImpl getXxpmItemMaster1() {
        return (XxpmItemMasterImpl)getAttributeInternal(XXPMITEMMASTER1);
    }

    /**
     * Sets <code>value</code> as the associated entity XxpmItemMasterImpl.
     */
    public void setXxpmItemMaster1(XxpmItemMasterImpl value) {
        setAttributeInternal(XXPMITEMMASTER1, value);
    }

    /**
     * @return the associated entity XxpmItemMasterImpl.
     */
    public XxpmItemMasterImpl getXxpmItemMaster2() {
        return (XxpmItemMasterImpl)getAttributeInternal(XXPMITEMMASTER2);
    }

    /**
     * Sets <code>value</code> as the associated entity XxpmItemMasterImpl.
     */
    public void setXxpmItemMaster2(XxpmItemMasterImpl value) {
        setAttributeInternal(XXPMITEMMASTER2, value);
    }

    /**
     * @return the associated entity XxpmItemMasterImpl.
     */
    public XxpmItemMasterImpl getXxpmItemMaster3() {
        return (XxpmItemMasterImpl)getAttributeInternal(XXPMITEMMASTER3);
    }

    /**
     * Sets <code>value</code> as the associated entity XxpmItemMasterImpl.
     */
    public void setXxpmItemMaster3(XxpmItemMasterImpl value) {
        setAttributeInternal(XXPMITEMMASTER3, value);
    }


    /**
     * @param weftId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence weftId) {
        return new Key(new Object[] { weftId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        try {
            super.lock();
        } catch (RowInconsistentException e) {
            refresh(REFRESH_WITH_DB_ONLY_IF_UNCHANGED | REFRESH_CONTAINEES);

            super.lock();
        }
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        try {
            super.doDML(operation, e);
        } catch (DMLConstraintException dce) {
            ma.showError(this.getDBTransaction(),
                         "Constraint: " + dce.getConstraintName() +
                         " voilated.");
            return;

        } catch (DMLException de) {
            String exception = de.getCause().toString();
            String msg =
                exception.substring(exception.indexOf(":", exception.indexOf("ORA")) +
                                    2);
            ma.showError(this.getDBTransaction(),
                         msg.substring(0, msg.indexOf("ORA") > 1 ?
                                          msg.indexOf("ORA") - 1 :
                                          msg.length()));
            return;

        } catch (Exception e1) {
            e1.printStackTrace();
            ma.showError(this.getDBTransaction(),
                         "There is an error in doDML method of XxpmWeftImpl. Class: " + e1.getClass());
            return;
        }
    }
    ModelActions ma = new ModelActions();
}
