package ncl.pm.model.bc.eo;

import java.util.ArrayList;
import java.util.Calendar;

import java.util.List;

import ncl.pm.model.bc.view.xxpmJC.CustomMap;
import ncl.pm.model.bc.view.xxpmJC.ModelActions;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.DMLConstraintException;
import oracle.jbo.DMLException;
import oracle.jbo.Key;
import oracle.jbo.RowInconsistentException;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 22 01:33:51 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxpmAbAccessoriesColorsImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AbAccColorId {
            public Object get(XxpmAbAccessoriesColorsImpl obj) {
                return obj.getAbAccColorId();
            }

            public void put(XxpmAbAccessoriesColorsImpl obj, Object value) {
                obj.setAbAccColorId((DBSequence)value);
            }
        },
        ArtBomAccId {
            public Object get(XxpmAbAccessoriesColorsImpl obj) {
                return obj.getArtBomAccId();
            }

            public void put(XxpmAbAccessoriesColorsImpl obj, Object value) {
                obj.setArtBomAccId((Number)value);
            }
        },
        ColorCode {
            public Object get(XxpmAbAccessoriesColorsImpl obj) {
                return obj.getColorCode();
            }

            public void put(XxpmAbAccessoriesColorsImpl obj, Object value) {
                obj.setColorCode((String)value);
            }
        },
        Selected {
            public Object get(XxpmAbAccessoriesColorsImpl obj) {
                return obj.getSelected();
            }

            public void put(XxpmAbAccessoriesColorsImpl obj, Object value) {
                obj.setSelected((Integer)value);
            }
        },
        CreatedBy {
            public Object get(XxpmAbAccessoriesColorsImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxpmAbAccessoriesColorsImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        },
        CreationDate {
            public Object get(XxpmAbAccessoriesColorsImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxpmAbAccessoriesColorsImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        },
        LastUpdatedBy {
            public Object get(XxpmAbAccessoriesColorsImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxpmAbAccessoriesColorsImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        },
        LastUpdateDate {
            public Object get(XxpmAbAccessoriesColorsImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxpmAbAccessoriesColorsImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        },
        RespId {
            public Object get(XxpmAbAccessoriesColorsImpl obj) {
                return obj.getRespId();
            }

            public void put(XxpmAbAccessoriesColorsImpl obj, Object value) {
                obj.setRespId((String)value);
            }
        },
        XxpmArticleBomAccessories {
            public Object get(XxpmAbAccessoriesColorsImpl obj) {
                return obj.getXxpmArticleBomAccessories();
            }

            public void put(XxpmAbAccessoriesColorsImpl obj, Object value) {
                obj.setXxpmArticleBomAccessories((XxpmArticleBomAccessoriesImpl)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxpmAbAccessoriesColorsImpl object);

        public abstract void put(XxpmAbAccessoriesColorsImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ABACCCOLORID = AttributesEnum.AbAccColorId.index();
    public static final int ARTBOMACCID = AttributesEnum.ArtBomAccId.index();
    public static final int COLORCODE = AttributesEnum.ColorCode.index();
    public static final int SELECTED = AttributesEnum.Selected.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY =
        AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE =
        AttributesEnum.LastUpdateDate.index();
    public static final int RESPID = AttributesEnum.RespId.index();
    public static final int XXPMARTICLEBOMACCESSORIES =
        AttributesEnum.XxpmArticleBomAccessories.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxpmAbAccessoriesColorsImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject =
                    EntityDefImpl.findDefObject("ncl.pm.model.bc.eo.XxpmAbAccessoriesColors");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for AbAccColorId, using the alias name AbAccColorId.
     * @return the AbAccColorId
     */
    public DBSequence getAbAccColorId() {
        return (DBSequence)getAttributeInternal(ABACCCOLORID);
    }

    /**
     * Sets <code>value</code> as the attribute value for AbAccColorId.
     * @param value value to set the AbAccColorId
     */
    public void setAbAccColorId(DBSequence value) {
        setAttributeInternal(ABACCCOLORID, value);
    }

    /**
     * Gets the attribute value for ArtBomAccId, using the alias name ArtBomAccId.
     * @return the ArtBomAccId
     */
    public Number getArtBomAccId() {
        return (Number)getAttributeInternal(ARTBOMACCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ArtBomAccId.
     * @param value value to set the ArtBomAccId
     */
    public void setArtBomAccId(Number value) {
        setAttributeInternal(ARTBOMACCID, value);
    }


    /**
     * Gets the attribute value for Selected, using the alias name Selected.
     * @return the Selected
     */
    public Integer getSelected() {
        return (Integer)getAttributeInternal(SELECTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Selected.
     * @param value value to set the Selected
     */
    public void setSelected(Integer value) {
        setAttributeInternal(SELECTED, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for RespId, using the alias name RespId.
     * @return the RespId
     */
    public String getRespId() {
        return (String)getAttributeInternal(RESPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RespId.
     * @param value value to set the RespId
     */
    public void setRespId(String value) {
        setAttributeInternal(RESPID, value);
    }

    /**
     * Gets the attribute value for ColorCode, using the alias name ColorCode.
     * @return the ColorCode
     */
    public String getColorCode() {
        return (String)getAttributeInternal(COLORCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ColorCode.
     * @param value value to set the ColorCode
     */
    public void setColorCode(String value) {
        setAttributeInternal(COLORCODE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public XxpmArticleBomAccessoriesImpl getXxpmArticleBomAccessories() {
        return (XxpmArticleBomAccessoriesImpl)getAttributeInternal(XXPMARTICLEBOMACCESSORIES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setXxpmArticleBomAccessories(XxpmArticleBomAccessoriesImpl value) {
        setAttributeInternal(XXPMARTICLEBOMACCESSORIES, value);
    }


    /**
     * @param abAccColorId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(DBSequence abAccColorId) {
        return new Key(new Object[] { abAccColorId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        try {
            super.lock();
        } catch (RowInconsistentException e) {
            refresh(REFRESH_WITH_DB_ONLY_IF_UNCHANGED | REFRESH_CONTAINEES);

            super.lock();
        }
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation != DML_DELETE) {
            if (operation == DML_INSERT) {
                this.setCreatedBy((String)ADFContext.getCurrent().getSessionScope().get("userID"));
                this.setCreationDate(new oracle.jbo.domain.Date(new java.sql.Timestamp(Calendar.getInstance().getTimeInMillis())));
            }
            this.setLastUpdatedBy((String)ADFContext.getCurrent().getSessionScope().get("userID"));
            this.setLastUpdateDate(new oracle.jbo.domain.Date(new java.sql.Timestamp(Calendar.getInstance().getTimeInMillis())));
            this.setRespId((String)ADFContext.getCurrent().getSessionScope().get("respID"));
        }
        try {
            List<CustomMap<Object, Object>> values =
                new ArrayList<CustomMap<Object, Object>>();
            values.add(new CustomMap(this.getPostedAttribute(this.getAttributeIndexOf("Selected")),
                                     this.getSelected()));
            ma.changeBomApprovalStatus(values,
                                       this.getXxpmArticleBomAccessories().getXxpmArticleBom());
            super.doDML(operation, e);
        } catch (DMLConstraintException dce) {
            ma.showError(this.getDBTransaction(),
                         "Constraint: " + dce.getConstraintName() +
                         " voilated.");
            return;

        } catch (DMLException de) {
            String exception = de.getCause().toString();
            String msg =
                exception.substring(exception.indexOf(":", exception.indexOf("ORA")) +
                                    2);
            ma.showError(this.getDBTransaction(),
                         msg.substring(0, msg.indexOf("ORA") > 1 ?
                                          msg.indexOf("ORA") - 1 :
                                          msg.length()));
            return;

        } catch (Exception e1) {
            e1.printStackTrace();
            ma.showError(this.getDBTransaction(),
                         "There is an error in doDML method of XxpmAbAccessoriesColorsImpl. Class: " +
                         e1.getClass());
            return;
        }
    }
    ModelActions ma = new ModelActions();
}
